### ISSUE TITLE
Meer Controls aan/uit kunnen zetten dan alleen de layerswitcher

### ISSUE THREAD

**Issue by milovanderlinden** [Geonovum/pdokkaart#163]
this.showzoom = Pdok.showzoom; // + - knop
    this.shownavigation = Pdok.shownavigation; // Kaart kunnen verscchuiven ja/nee
    this.showscaleline = Pdok.showscaleline; //schaal tonen ja/nee
    this.showmouseposition = Pdok.showmouseposition; //coordinaten tonen ja/nee
    this.geocoder = Pdok.geocoder; //geocoder actief (zoekfunctionaliteit) ja/nee

**Comment by rduivenvoorde** [comment]
Milo: "Nee. Dit behoort niet tot mijn takenpakket en ik heb geen budget gekregen van RWS om dit in eigen tijd te doen."
