### ISSUE TITLE
Mogelijkheid om eigen lagenlijsten samen te stellen

### ISSUE THREAD

**Issue by ndkv** [Geonovum/pdokkaart#166]

**Comment by ndkv** [comment]
In principe kan dit al, het moet enkel beschreven worden in de documentatie.

**Comment by JeroenBaltussen** [comment]
Je zou de wizard op kunnen starten met een parameter die verwijst naar de voorgedefinieerde kaartlagen.
Maar hoe?

**Comment by ndkv** [comment]
Je kan een lijstje definieren in de configuratie, zie "layersdef" property in http://pdokkaart.readthedocs.org/en/latest/#javascript-api

**Comment by rduivenvoorde** [comment]
Een 'standaard wizard' met de pdok-lagen en markers:

http://zuidt.nl/pdokkaart/

(zoals je ziet, een hele trits layers en markers).

Nu heb ik twee js files neergezet:

http://zuidt.nl/zuidt-layers.js

http://zuidt.nl/zuidt-markers.js

en die definieren andere en veel kortere marker- en layerlijsten.
Door de wizard op deze manier aan te roepen:

http://zuidt.nl/pdokkaart/?layersdef=http://zuidt.nl/zuidt-layers.js&markersdef=http://zuidt.nl/zuidt-markers.js

Zie je dus andere (ondergrond)kaartlagen en te gebruiken markers. Nu kun je dus voor een bepaalde dienst of gemeente een relevante wizard aanbieden.

Met bovenstaande wizard kun je dus bv zo'n kaartje maken:

http://zuidt.nl/pdokkaart/api/api.html?mapdiv=map_vialink&zoom=3&showlayerswitcher=true&showzoom=true&shownavigation=true&showscaleline=true&showmouseposition=true&loc=170430.08%2C%20470430.08&markersdef=http%3A%2F%2Fzuidt.nl%2Fzuidt-markers.js&layersdef=http%3A%2F%2Fzuidt.nl%2Fzuidt-layers.js&mloc=138389.12%2C471720.32&titel=%26nbsp%3B&mt=mt1&pdoklayers=ZUIDT_TOPO
