### ISSUE TITLE
crossdomain

### ISSUE THREAD

**Issue by milovanderlinden** [Geonovum/pdokkaart#167]
Kortgeleden kwam het bericht dat PDOK de crossdomain instellingen goed heeft gezet. Hierdoor zou het in theorie niet meer nodig zijn om voor de PDOK geocoder en getfeatureinfo requests een proxy(script) te gebruiken.

**Comment by rduivenvoorde** [comment]
we kunnen er voor de generieke pdokkaart niet vanuit gaan dat er alleen PDOK services worden gebruikt. Er zijn ook de mogelijkheden om eigen services etc toe te voegen. Het goed zetten van die headers is voor veel gebruikers nog een brug te ver.

Vooralsnog zou ik dus het gebruik van proxy(scripts) niet willen verwijderen.
