### ISSUE TITLE
Geometrie van via URL ingelezen KML wordt niet herkend

### ISSUE THREAD

**Issue by ndkv** [Geonovum/pdokkaart#171]
Uit de [forum](https://www.pdok.nl/nl/forums/pdok-technische-onderwerpen/02apr15-problemen-bij-software-broncode-pdok-kaart):

" Wanneer ik een externe url opgeef om een kml bestand in te lezen (bij markers) krijg ik de volgende foutmelding: 

Unable to get property 'addFeaturesFromString' of undefined or null reference.
Regel:1985 van pdok-api.js:
// we have data now: add to map this.passthroughPdokObject.addFeaturesFromString(data, this.dataType, this.zoomToFeatures);

De data wordt wel opgehaald (geen proxy error of een onbereikbaar bestand foutmelding) maar heeft kennelijk moeite de data te verwerken. Wanneer ik de data uit het kml bestand kopieer en plak in copy/paste scherm wordt data wel correct ingelezen. Iemand ervaring of een oplossing? "

**Comment by rduivenvoorde** [comment]
ik heb gereageerd in het forum. Zal deze issue nog even openlaten tot ik daaruit commentaar/input terug krijg

**Comment by rduivenvoorde** [comment]
ik sluit deze omdat het op een extern code probleem lijkt, niet iets van de api zelf
