### ISSUE TITLE
#search css style conflicteert met CMS

### ISSUE THREAD

**Issue by milovanderlinden** [Geonovum/pdokkaart#172]
Wanneer de pdokkaart wordt geembed in b.v. een CMS dan is er de mogelijkheid dat de css klasse #search in de api.css in conflict raakt. Is het niet een beter idee om hier een andere ID op te zetten die te relateren is aan PDOK?

**Comment by Geoneer** [comment]
Welke app gebruik je dan? pdokviewer van Geonovum? Je kan ook hier kijken: 

#1: https://github.com/boundlessgeo/GeoExplorer
#2: https://github.com/Geoneer/GeoExplorer 



From: Milo van der Linden 
Sent: Wednesday, April 29, 2015 3:29 PM
To: Geonovum/pdokkaart 
Subject: [pdokkaart] #search css style conflicteert met CMS (#172)

Wanneer de pdokkaart wordt geembed in b.v. een CMS dan is er de mogelijkheid dat de css klasse #search in de api.css in conflict raakt. Is het niet een beter idee om hier een andere ID op te zetten die te relateren is aan PDOK?

**Comment by rduivenvoorde** [comment]
hi Milo, geen probleem. Ik zal het aanpassen.

@Geoneer wat heeft dit nou te maken met dit project??? Geoexplorere is een totaal ander project en heeft ook niks te maken met naamgeving van css'en??

**Comment by Geoneer** [comment]
geen idee.. just in case. Heb ooit het project PDOK viewer opgestart. Verbaasde mij er nog over dat het nog leeft. zie het nergens gebruikt worden....

**Comment by milovanderlinden** [comment]
Misschien moet je beter kijken ;-)

https://github.com/RWS-CIV-IRN-TBP/pdokkaart-applicaties

**Comment by rduivenvoorde** [comment]
fixed in https://github.com/Geonovum/pdokkaart/commit/424d53ca4f6fad0636238152dcea0417525b0cd3
