### ISSUE TITLE
FeatureRequest: start viewer met ingeklapte layermanager

### ISSUE THREAD

**Issue by rduivenvoorde** [Geonovum/pdokkaart#173]
Bij PdokKaart wizard heb je standaard de mogelijkheid om WEL of GEEN layerswitcher/knop_kaartlagen te tonen.

Als je 'm WEL laat zien dan zal hij in de kaart ook geopend zijn.

Nu is de vraag vanuit Rijkswaterstaat of de layerswitcher niet standaard INgeklapt kan zijn wanneer hij WEL aanwezig is.

Dit zou een verandering zijn van het huidige gedrag, dus vandaar dat ik het even zo ter discussie breng.
Er zit, zeker in het geval van het gebruik van kleine kaartjes in een cms of gewoon kleine devices wel iets in om dit zo te doen en de kaart het hoofdonderdeel te laten zijn.

Comments?

**Comment by raymondnijssen** [comment]
Goed punt, zeker mobiel!
Voordeel van uitgeklapt opstarten is dat gebruikers dan de layers zien en kunnen wegklappen. Bij een ingekapte start weten veel gebruikers niet waar dat plusje voor dient denk ik.

**Comment by milovanderlinden** [comment]
+1

**Comment by ndkv** [comment]
+1

Mocht iemand er toch moeite mee hebben kunnen we een 'in/uitgeklapt' 
switch bouwen.

**Comment by beheerPDOK** [comment]
Goed idee inderdaad voor kleinere devices maar het + symbool valt daarentegen m.i. niet heel erg op. Het ligt wat mij betreft dan ook aan het type gebruiker. Ik zou eerlijk gezegd gelijk de switch zoals door Simeon genoemd inbouwen. Hiermee loop je niet het risico dat voor gebruikers van de huidige versie het een "stap terug" is en biedt een extra functionaliteit voor RWS...?

**Comment by rduivenvoorde** [comment]
maar elke switch moet ook weer in de url/config komen. In mijn optiek zitten er al veel te veel switches intussen in. Url wordt alleen maar langer en onoverzichtelijker in mijn ogen.

**Comment by beheerPDOK** [comment]
Dat is ook waar.. Wat mij betreft dan inderdaad ook aanpassen. Als er veel commentaar op komt dan kunnen we daar altijd nog op acteren!

**Comment by ndkv** [comment]
Je kan gebruikers attenderen op beschikbaarheid van meerdere lagen in 
tekst waar kaart bij hoort (indien het een embed is). Op mobiele devices 
zal het wel opvallen omdat er geen andere controls/tekst aanwezig is 
(mits kaart fullscreen is).
