### ISSUE TITLE
Zoeken op KML in RedTheDocs levert geen resultaten op terwijl woord wel in tekst voorkomt

### ISSUE THREAD

**Issue by ndkv** [Geonovum/pdokkaart#183]

**Comment by JeroenBaltussen** [comment]
Heb je idee waarom zoek niet altijd goed werkt?

**Comment by ndkv** [comment]
Nog niet.

Je kan ook via ReadTheDocs projectpagina zoeken en dat werkt wel, zie 
https://readthedocs.org/projects/pdokkaart/search/?q=kml

Lijkt er op dat ik ergens een instelling goed moet zetten om betere 
search aan de voorkant aan te zetten.

**Comment by ndkv** [comment]
Werkt weer.
