### ISSUE TITLE
cross-site-scripting PDOK Kaart

### ISSUE THREAD

**Issue by beheerPDOK** [Geonovum/pdokkaart#196]
Via een zogenaamde cross-site-scripting-aanval kan een aanvaller JavaScript-code invoegen in een (X)HTML-document. Deze code wordt uitgevoerd in de webbrowser van de gebruiker, in de context van het document. Tijdens het toevoegen van een nieuwe laag is het mogelijk om HTML-code toe te voegen, die in de browser van de gebruiker wordt uitgevoerd op het moment dat de kaart bekeken wordt. Een aanvaller kan getoonde informatie zo prepareren dat wanneer een andere gebruiker (in het bijzonder een beheerder) een specifieke pagina bezoekt, de aanvaller toegang kan verkrijgen tot de gegevens van het slachtoffer en acties als het slachtoffer kan uitvoeren. 
In dit geval is er sprake van een reflected cross-site-scripting-kwetsbaarheid. Hier moet de geïnjecteerde code in een HTTP-request meegegeven worden. In deze situatie zal de aanvaller door middel van social-engineering-technieken het slachtoffer eerst zover moeten krijgen dat deze een url onder controle van de aanvaller bezoekt. Wanneer gebruikersinvoer in (X)HTML-documenten wordt opgenomen, dienen metatekens (afhankelijk van de context) te worden geëscapet. 
In HTML-elementen betekent dit dat de tekens <, >, en & geëscapet moeten worden, door ze te vervangen door respectievelijk de tekenreeksen &lt;, &gt; en &amp;. In waarden van attributen moet afhankelijk van de gebruikte aanhalingstekens het teken ' of " vervangen worden door respectievelijk &#x27; (in XHTML mag &apos; ook) of &quot;. Valideer ook de gebruikersinvoer. Zorg er hierbij voor dat alleen gewenste tekens worden geaccepteerd.

**Comment by rduivenvoorde** [comment]
Mmm, kun je dit iets concreter maken?

Die wizard is natuurlijk niet een doorsnee pagina, je moet daar inderdaad een url invoeren die daarna in je javascript komt. Bijna per definitie gaan we daar cross-site (vandaar ook de proxy).

Waar wil je precies <  > &  escapen?

**Comment by beheerPDOK** [comment]
@rduivenvoorde we hebben het nog even aan een interne specialist voorgelegd en hij geeft aan dat het een non-issue is (zijn reactie: volgens mij is dit een non-issue, deze tool helpt met name om een stuk code te genereren zodat je een kaart viewer in je eigen website zou kunnen embedden. Mijn mening is dat de gebruiker van deze kaart tool zelf verantwoordelijk is voor het screenen van de code die ze gaan opnemen binnen hun eigen content). Voor nu geen actie en zullen we het issue sluiten.
