### ISSUE TITLE
Adres opgeven als parameter

### ISSUE THREAD

**Issue by LuukS** [Geonovum/pdokkaart#204]
Als beheerder van een willekeurige website (bv https://www.rvo.nl/over-rvonl/contact/vestigingen) wil ik een link naar een locatie op basis van een adres kunnen opnemen. Dit wil ik kunnen doen met de PDOK Kaart.
Concreet zou ik een url als de volgende willen kunnen maken welke na openen inzoomt op de gevonden locatie: https://kaart.pdok.nl/api/api.html?adres=Mandemaat 3,Assen

**Comment by LuukS** [comment]
Een andere optie zou zijn om het te doen zoals Google Maps. Deze gebruikt de parameter ?q=<adres> Bijvoorbeeld http://maps.google.com/?q=Mandemaat%203,Assen. Voor PDOKKaart zou dan de url https://kaart.pdok.nl/api/api.html?q=Mandemaat%203,Assen werkend gemaakt moeten worden.

**Comment by JeroenBaltussen** [comment]
Met de PDOK Kaartwizard  (https://kaart.pdok.nl/) kun je eenvoudig een link maken met een prachtige marker. :)

https://kaart.pdok.nl/api/api.html?mapdiv=map_vialink&zoom=13&loc=234105%2C%20555240& &mloc=234077.7%2C555297.96&titel=RVO&tekst=Mandemaat%203%3Cbr%2F%3EAssen%3Cbr%2F%3E&mt=mt0

**Comment by LuukS** [comment]
Ik heb het gemaakt. Er is nu in de API een parameter q waaraan een adres kan worden opgegeven. Het moet wel een volledig adres zijn: straatnaam huisnummer, plaatsnaam.

**Comment by LuukS** [comment]
Kijk in de voorbeelden wat er nog meer mogelijk is met het zoeken op adres (zie de voorbeelden 28, 29 en 30). Op het moment van schrijven is voorbeeld 30 nog niet opgenomen op https://kaart.pdok.nl/examples/ maar wel op http://geonovum.github.io/pdokkaart/examples/)
